### ISSUE TITLE
Relation Prediction

### ISSUE THREAD

**Issue by Demirrr** [IBCNServices/pyRDF2Vec#12]
Hello all,
firstly I would like to thank you for a clean implementation. Finally, we have clearn implementation of RDF2Vec to play with :) 

I was wondering whether one use  RDF2Vec in link prediction task on benchmark datasets like FB15k-237 or WN18RR that are can be found in https://github.com/ibalazevic/TuckER/tree/master/data.

Given subject and object, I would like to perform predicate predication by using RDF2Vec. Any thoughts or scripts are appreciated.

Cheers

**Comment by GillesVandewiele** [comment]
Hi @Demirrr 

My apologies for this overly late reply... I did not know how to answer it directly, since I had never done link prediction before. A naive approach would be to create representations and then create a dataset in which you create positive and negative examples by combining representations between which there is either a or no link respectively.

![Screenshot from 2020-09-09 16-54-18](https://user-images.githubusercontent.com/5750603/92615384-58c0ea00-f2bd-11ea-929a-3cbfef738326.png)

**Comment by rememberYou** [comment]
I assume that this issue has been resolved. Feel free to react again if the issue has not been resolved.
