### ISSUE TITLE
Deal with large files

### ISSUE THREAD

**Issue by dinani65** [IBCNServices/pyRDF2Vec#33]
Hi
In order to generate  embedding of entities when the size of input KG file is approximately large, what should we do? particularly when the remote KG is also so slow.
Thanks in advance for your reply,
with regards,

**Comment by rememberYou** [comment]
Currently, `pyRDF2Vec` doesn't scale to larger KGs as it implicitly asks to load the whole KG in memory. 
The next release will make sure to provide a solution to this problem by make it possible to extract the walks by only loading parts into memory and/or by querying SPARQL endpoint on a server and in particular by using a caching mechanism, in order to have better performance.

**Comment by GillesVandewiele** [comment]
Hi @dinani65,

I think for now, the fastest solution would be to set up your own local SPARQL endpoint and then use that for the Remote KG. This should avoid delays caused by HTTP requests (which are very significant). If time allows, I might test this myself on some larger KG such as DBpedia.

**Comment by GillesVandewiele** [comment]
Hi @dinani65 

@bsteenwi was so kind to make a wiki-page on how you can set-up your own local server and what the impact of it is (SPOILER: you get a speedup of several orders of magnitude). Please find it here: https://github.com/IBCNServices/pyRDF2Vec/wiki/Fast-generation-of-RDF2Vec-embeddings-with-a-SPARQL-endpoint

**Comment by dinani65** [comment]
I greatly appreciate the all
