### ISSUE TITLE
Abstract graph query implementation

### ISSUE THREAD

**Issue by bsteenwi** [IBCNServices/pyRDF2Vec#37]
Maybe it is a good idea to also abstract this part of the code and provide 'connectors'.
By doing this, we can e.g. also load NTRIPLE files directly into our KG representation without the need of RDFLib or an endpoint.

https://github.com/IBCNServices/pyRDF2Vec/blob/470d1a6167163b37787e251b610a91627a5d667a/pyrdf2vec/graphs/kg.py#L92

**Comment by LarsAC** [comment]
+1

I modified the code to use pystardog and there are many more ways to get hold of the data.

**Comment by GillesVandewiele** [comment]
Hi @LarsAC 

Thanks for chipping in! Out of curiosity, could you perhaps share the code you used? It could perhaps be useful once we start dealing with this issue :).

**Comment by LarsAC** [comment]
I wasn't a fancy implementation. I subclassed the KG class, overriding __init__ to use the location argument as a dict holding server / port / username / password so that I can create a stardog client object which is then used in _get_shops (also overridden). 

I guess the better design would be to provide a separate connector object with a query method that could have implementations using local rdf files, SPARQLWrapper or proprietary libraries for graph databases / triple stores.

**Comment by rememberYou** [comment]
A first implementation version for connectors has been committed (https://github.com/IBCNServices/pyRDF2Vec/commit/c3abce108ca313e78feea11b0d6c7c3595419ae5).

This commit allows to use `SPARQLConnector` which has all the functions related to the fetch of remote hops on a SPARQL endpoint server. This is only a first draft which aims to minimize the `KG` class. Any pull request is welcome.

**NOTE:** the `Vertex` class has been separated from the KG class to avoid circular import problems, since the `Vertex` type is used everywhere in pyRDF2Vec.
