### ISSUE TITLE
Weird b'... elements created during walks

### ISSUE THREAD

**Issue by VMul** [IBCNServices/pyRDF2Vec#48]
## ❓ Question

I'm currently working with RDF2Vec and I noticed, that these weird b'… descriptors (e.g. b'\x96]x\xe9\xaf\xbaTu') are used in the sentences during the walks. Are these kind of placeholders?

If yes, is there a way to display the real name of the element/entity?

**Comment by GillesVandewiele** [comment]
Hi @VMul,

You are correct. A typical walk extracted by pyRDF2Vec has the following format:
```
('http://dx.doi.org/10.3389/fmicb.2012.00075',
  'http://purl.org/spar/cito/cites',
  "b'\\x96]x\\xe9\\xaf\\xbaTu'",
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
  "b'V\\x8c\\x1d|Y%\\xa2\\xa9'")
  ```

Here, we see that the hops on the **even** positions, except the root (position 0), are bytestrings. This is done on purpose by pyRDF2Vec. We hash all entities that are not the root of a walk or a predicate in order to reduce the memory usage. 

To illustrate how this reduces memory usage, one could take a look at a typical dbpedia page, such as the one of the beautiful country [Belgium](https://dbpedia.org/page/Belgium). Here we see that the `dbo:abstract` is typically a rather long text that requires many bytes to be stored. Therefore we decide to hash this to a fixed amount of bytes (by default 8).

Since Word2Vec internally works with a one-hot-encoded bag-of-words representation, the syntactical form of the hops **do not matter**. So whether you provide a hash such as `b'\x96]x\xe9\xaf\xbaTu'` or plaintext such as `Belgium` to word2vec, the effect will be the same.

As of the newest version of pyRDF2Vec, we allow the user to configure this hashing procedure. The user can allocate more bytes per hash to avoid collisions, or just disable the hashing in order to get sensible walks.

To do this, you have to use the `md5_bytes` keyword while creating a Walker-object. As an example: here's a random walker that will extract all possible walks exhaustively of depth 4, without hashing: `walker = RandomWalker(4, None, md5_bytes=None)`


Hope this clears it up! If not, feel free to ask additional questions.

**Comment by VMul** [comment]
Thank you very much for your answer!
That cleared it up for me.
