### ISSUE TITLE
nest_asyncio is not added in pyproject.toml

### ISSUE THREAD

**Issue by moritzblum** [IBCNServices/pyRDF2Vec#62]
## 🐛 Bug

Hi all, 

my installation from source throws the following Error:

## Current Behavior
```
Traceback (most recent call last):
  File "playground.py", line 3, in <module>
    from pyrdf2vec import RDF2VecTransformer
  File "/home/mblum/anaconda3/envs/rdf2vec/lib/python3.8/site-packages/pyrdf2vec/__init__.py", line 1, in <module>
    import nest_asyncio
ModuleNotFoundError: No module named 'nest_asyncio'
```

## Steps to Reproduce
1. conda create --name rdf2vec python=3.8
2. conda activate rdf2vec
3. git clone https://github.com/IBCNServices/pyRDF2Vec.git
4. cd pyRDF2Vec/
5. pip install .
6. pip install pandas
7. python playground.py (getting started example)

**Comment by GillesVandewiele** [comment]
Hi @moritzblum,

Thank you for your interest in pyRDF2Vec and for reporting this bug. It indeed seems that we have forgot to add nest_asyncio to the requirements in our [pyproject.toml](https://github.com/IBCNServices/pyRDF2Vec/blob/master/pyproject.toml). Just to make sure: could you manually install nest_asyncio (through conda or pip) and see if it then runs?

**Comment by moritzblum** [comment]
Hi @GillesVandewiele,

thats the problem, now it works! Thank you. :+1:

**Comment by rememberYou** [comment]
It's weird that you have to install `nest_asyncio`, because the `nest-asyncio` package is already specified as a dependency with pyRDF2Vec. To prevent this problem from happening again, I also specified `nest_asyncio`, as suggested (cf. [b95f6dc5420bed2b94e12ddb3d4ee1cb11c2cb05](https://github.com/IBCNServices/pyRDF2Vec/commit/b95f6dc5420bed2b94e12ddb3d4ee1cb11c2cb05)), which like `nest-asyncio` is in itself a temporary package that can be removed in the future.

I also created a `docker-compose` and a `Dockerfile` file for installing these dependencies with `poetry` and otherwise facilitating pyRDF2Vec contributions (cf. [2ea1af9af50f61e0d851ee08fe1f94073e33122c](https://github.com/IBCNServices/pyRDF2Vec/commit/2ea1af9af50f61e0d851ee08fe1f94073e33122c)). With a simple command, a Jupyter notebook with the dependencies already installed can now be used :-)

**Comment by GillesVandewiele** [comment]
Thank you so much @rememberYou  <3! This is greatly appreciated.
